title: "Hash Selector Patter"
tags: ["Ruby"]
playlists: ["A Shot of Ruby"]
publish: true
details:
  blurb: "We show you an alternative to if / case"
  cover: "assets/has-selector-icon.png"
  video: "http://www.youtube.com/watch?v=Pyg-31Nhd8I"