title: "Filling out Mobile Site UI (Variants + Framework7)"
tags: ["Rails", "Framework7", "Mobile", "Variants"]
publish: true
details:
  blurb: "In this episode we fill out the mobile site ui that we setup in our rails app."
  cover: "assets/filling-out-mobile-ui.png"
  video: "http://www.youtube.com/watch?v=13IQEGjjt5s"
  color: "amethyst"
