title: "Ruby Project Introduction"
tags: ["Ruby"]
playlists: ["Ruby From Scratch"]
publish: true
details:
  blurb: "We give the Ruby From Scratch course a context."
  cover: "assets/ruby-project.png"
  video: "http://www.youtube.com/watch?v=VqrNPtrIp1c"
  color: "orange"
