title: "Minimizing Computation"
tags: ["Rails", "Optimization"]
publish: true
details:
  blurb: "We show you some techniques to help you minimize computation in your app."
  cover: 'assets/minimize.png'
  color: "amethyst"