title: "Installing Ruby"
tags: ["DevOps"]
playlists: ["DevOps for Developers"]
publish: true
details:
  blurb: "Setting up Ruby on your server"
  video: "http://www.youtube.com/watch?v=mMMH0qPXRXc"
  cover: 'assets/ruby.png'
  color: "alizarin"