title: "Extracting data from a String"
tags: ["Ruby"]
playlists: ["Ruby From Scratch"]
publish: true
details:
  blurb: "We show you how to use the String#split to extract data"
  cover: "assets/ruby-string-split.png"
  color: "amethyst"
  video: "http://www.youtube.com/watch?v=V8fKfen6Pvc"

