title: "How we Create Content for Codemy"
tags: ["Writefully"]
playlists: ["Open Source Projects"]
publish: true
details:
  blurb: "This is a sample post for Writefully"
  cover: "assets/writefully-icon.png"
  color: "orange"
  video: "http://www.youtube.com/watch?v=TgSZKVTIUYM"
