title: "How a VPN Works"
tags: ["Devops", "VPN"]
playlists: ["Devops for Developers"]
publish: false
details:
  blurb: "We discuss the details of how a vpn works, and why you would want to have one."
  cover: "assets/vpn-icon.png"
  color: "wisteria"
  video: "http://www.youtube.com/watch?v=zpUHD-PQuZg"
