title: "Basic Ruby Data Types"
tags: ["Ruby"]
playlists: ["Ruby From Scratch"]
publish: true
details:
  blurb: "This is a sample post for Writefully"
  cover: "assets/ruby.png"
  color: "alizarin"
  video: "http://www.youtube.com/watch?v=eu9EANbq2yk"
