title: "Spruce up your Shell with Oh My ZSH"
tags: ["Development Tools"]
playlists: ["Sauce of the Week"]
publish: true
details:
  blurb: "We show you oh-my-zsh"
  cover: "assets/oh-my-zsh.png"
  color: 'nephritis'
  video: "http://www.youtube.com/watch?v=9jACAQ4MHWs"
