title: "Framework 7 for Mobile Happiness"
tags: ["Rails", "Mobile", "Framework7"]
playlists: ["A Shot of Ruby"]
publish: false
details:
  blurb: "Integrate Framework7 into your rails application."
  color: "emerland"