title: "Mina For Deployment"
tags: ["DevOps"]
playlists: ["DevOps for Developers"]
publish: true
details:
  blurb: "Get up and running with Mina deployment tool"
  cover: 'assets/mina.png'
  color: "pumpkin"