title: "Methods, Arguments and Keyword Arguments"
tags: ["Ruby"]
playlists: ["Ruby from Scratch"]
publish: true
details:
  blurb: "In this episode we talk about methods, arguments and keyword arguments"
  cover: "assets/methods-arguments.png"
  color: 'amethyst'
