title: "Git Deployment"
tags: ["DevOps"]
playlists: ["DevOps for Developers"]
publish: true
details:
  blurb: "Setup a basic git deployment"
  video: "http://www.youtube.com/watch?v=wFHlMytsMgk"
  cover: 'assets/git.png'
  color: "pumpkin"