title: "Getting Started with Writefully"
tags: ["Writefully"]
playlists: ["Open Source Projects"]
publish: true
details:
  blurb: "We show you how to get up and running with the writefully gem"
  cover: "assets/writefully-icon.png"
  color: "alizarin"
  video: "http://www.youtube.com/watch?v=dV0Asq95Brs"
