title: "Rails 4.1 Enum"
tags: ["Rails"]
publish: false
details:
  blurb: "We show you why and how you would use enum in your app"
  cover: "assets/enum-icon.png"
  color: "belize-hole"
  video: "http://www.youtube.com/watch?v=UbOkNduhCfw"
