title: "Nginx Setup"
tags: ["DevOps"]
playlists: ["DevOps for Developers"]
publish: true
details:
  blurb: "We show you how to setup Nginx on your server"
  video: "http://www.youtube.com/watch?v=TIaBrUo2944"
  cover: 'assets/cover.png'