title: "Analytics with Redis Part 1"
tags: ["Redis", "Ruby", "Nosql"]
playlists: ["A Shot of Ruby"]
publish: false
details:
  blurb: "How to build a basic analytics system with Redis."
  cover: "assets/cover.png"
  video: ""